### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by guilyx** [master-coro/artin-pathfinding#12]
Instead of generating an ugly command-line matrix, maybe do a graph based GUI ? Or a B&W availability grid with the path in color ?

**Comment by sampreets3** [comment]
That will require a separate program may be so that the output of the solution can be piped on to the input of the application. I will try and implement a solution using python.

for the B&W availability grid, we can modify the code from ARPRO-Maze I guess.

**Comment by guilyx** [comment]
Create classes used for the GUI in gui.py in lib was my first idea, then write in src the python file that will pipe everything. Object oriented approach would allow us to reuse the way we made the GUI for later projects, could be cool

For the grid, I thought the same but it would require to use opencv !

I'm a noob with GUIs and I have other things with higher priority but if you want to do it I could assign you in the issue 👍 

List of links for PyQt if you want :
- https://doc.qt.io/qtforpython/
- https://doc.qt.io/qtforpython/quickstart.html
- https://doc.qt.io/qtforpython/tutorials/index.html

QtQuick/QML requires Javascript, but I think gives much better results if you want to look into it

**Comment by sampreets3** [comment]
I don't have much experience with GUIs either. Don't really prefer them, to be honest. I will try and write an implementation of the gui.py if possible. I will start a PR if I finish the implementation

**Comment by guilyx** [comment]
Paths are now displayed with matplotlib, but still no option to run from a GUI, because too lazy for GUIs :oops:
